import type { ElementTypeIri, ElementModel } from '../data/model';
import type * as Rdf from '../data/rdf/rdfModel';
import { rdfs, schema, xsd } from '../data/rdf/vocabulary';

/**
 * Provides a strategy to upload files from the UI, e.g. forms.
 *
 * @category Core
 */
export interface FileUploadProvider {
    /**
     * Uploads a file, generates and returns its metadata.
     */
    uploadFile(file: File, options: { signal?: AbortSignal }): Promise<UploadedFile>;
    /**
     * Gets metadata for a file uploaded with this provider instance.
     */
    getFileMetadata(fileIri: string): ElementModel | undefined;
    /**
     * Gets or creates a resolvable asset URL for a file uploaded
     * with this provider instance.
     *
     * @returns a URL that can be used in `<a href="...">` or `<img src="...">`
     *   or `undefined` if the specified IRI does not correspond to an uploaded file
     *   with this provider instance
     */
    resolveFileUrl(
        fileIri: string,
        options: { signal?: AbortSignal }
    ): Promise<string | undefined>;
}

/**
 * Represents an uploaded file.
 *
 * @see {@link FileUploadProvider}
 */
export interface UploadedFile {
    /**
     * Unique file IRI, generated by the upload provider.
     */
    readonly iri: string;
    /**
     * File metadata, generated by the upload provider.
     *
     * Depending on the provider, may contain these or other properties:
     *  - `rdfs:label` with original file name, e.g. `my_picture.png`;
     *  - `schema:encodingFormat` with file MIME-type, e.g. `image/jpeg`;
     *  - `schema:fileSize` with file size, e.g. `1024B`;
     *  - `schema:uploadDate` with the upload date and time, e.g. `2026-01-01T12:00:00Z`.
     */
    readonly metadata: ElementModel;
}

/**
 * Default entity type for an {@link UploadedFile uploaded file}.
 *
 * @category Constants
 */
export const FileType: ElementTypeIri = 'urn:reactodia:File';

/**
 * Represents an file uploaded with {@link MemoryFileUploader}.
 *
 * @see {@link MemoryFileUploader}
 */
export interface MemoryUploadedFile extends UploadedFile {
    /**
     * Unique file name, generated by the upload provider.
     *
     * The value might be based on or be completely different from the original file name.
     */
    readonly name: string;
    /**
     * In-memory file content as a `Blob`.
     */
    readonly blob: Blob;
}

/**
 * Options for {@link MemoryFileUploader}.
 */
export interface MemoryFileUploaderOptions {
    /**
     * RDF/JS-compatible term factory to create RDF terms.
     */
    factory: Rdf.DataFactory;
    /**
     * Signal to dispose the provider and revoke all resolved file URLs.
     */
    disposeSignal: AbortSignal;
}

/**
 * File upload strategy which stores the file content and metadata in-memory.
 *
 * @category Core
 */
export class MemoryFileUploader implements FileUploadProvider {
    private static readonly IRI_PREFIX = 'urn:reactodia:memory-file:';

    private readonly factory: Rdf.DataFactory;
    private readonly disposeSignal: AbortSignal;
    private readonly uploadedFiles = new Map<string, MemoryUploadedFile>();
    private readonly objectUrls = new WeakMap<MemoryUploadedFile, string>();

    constructor(options: MemoryFileUploaderOptions) {
        const {factory, disposeSignal} = options;
        this.factory = factory;
        this.disposeSignal = disposeSignal;
        this.disposeSignal.addEventListener('abort', () => {
            for (const file of this.uploadedFiles.values()) {
                const objectUrl = this.objectUrls.get(file);
                if (objectUrl) {
                    URL.revokeObjectURL(objectUrl);
                }
            }
            this.uploadedFiles.clear();
        });
    }

    /**
     * Gets an iterator over all files uploaded via this provider instance.
     */
    files(): Iterable<MemoryUploadedFile> {
        return this.uploadedFiles.values();
    }

    getFileMetadata(fileUrl: string): ElementModel | undefined {
        return this.uploadedFiles.get(fileUrl)?.metadata;
    }

    async uploadFile(file: File, options: { signal?: AbortSignal; } = {}): Promise<UploadedFile> {
        const { signal } = options;
        signal?.throwIfAborted();
        this.disposeSignal.throwIfAborted();
        const timestamp = new Date().toISOString().replaceAll(/[Z\s:-]/g, '');
        const name = `${timestamp}_${file.name}`;
        const iri = MemoryFileUploader.IRI_PREFIX + name;
        const uploaded: MemoryUploadedFile = {
            iri,
            name,
            metadata: {
                id: iri,
                types: [FileType],
                properties: {
                    [rdfs.label]: [this.factory.literal(file.name)],
                    [schema.encodingFormat]: file.type ? [this.factory.literal(file.type)] : [],
                    [schema.fileSize]: [this.factory.literal(`${file.size}B`)],
                    [schema.uploadDate]: [
                        this.factory.literal(
                            new Date().toISOString(),
                            this.factory.namedNode(xsd.dateTime)
                        )
                    ],
                },
            },
            blob: file,
        };
        this.uploadedFiles.set(uploaded.metadata.id, uploaded);
        return uploaded;
    }

    async resolveFileUrl(fileIri: string, options: { signal?: AbortSignal }): Promise<string | undefined> {
        return this.resolveFileUrlSync(fileIri);
    }

    private resolveFileUrlSync(fileIri: string): string | undefined {
        const file = this.uploadedFiles.get(fileIri);
        if (!file) {
            return undefined;
        }
        let objectUrl = this.objectUrls.get(file);
        if (!objectUrl) {
            objectUrl = URL.createObjectURL(file.blob);
            this.objectUrls.set(file, objectUrl);
        }
        return objectUrl;
    }
}
